name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Install backend dependencies
      run: npm install --prefix server

    - name: Build backend
      run: npm run build --prefix server

    - name: Install PM2 globally
      run: npm install pm2 -g

    - name: Deploy frontend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./client/*"
        target: "/var/www/html/sabus_cubs/"

    - name: Deploy backend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./server/server/*"
        target: "/var/www/html/sabus_cubs/"

    - name: Restart backend with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/sabus_cubs/
          npm install --prefix server # Install backend dependencies
          pm2 restart all || pm2 start server/server.js --name sabus_cubs
