name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    # Install and build frontend
    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    # Install backend dependencies and build backend
    - name: Install backend dependencies
      run: npm install --prefix server

    - name: Build backend
      run: npm run build --prefix server

    # Copy necessary non-code files into the api directory
    - name: Prepare backend for deployment
      run: |
        cp server/package.json api/package.json
        cp -R server/public api/public
        
    # Deploy frontend to Digital Ocean
    - name: Deploy frontend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./client/*"
        target: "/var/www/html/sabus_cubs/"

    # Deploy backend to Digital Ocean
    - name: Deploy backend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./api/*"
        target: "/var/www/html/sabus_cubs/"

    # Restart backend with PM2
    - name: Restart backend with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/sabus_cubs/api
          npm install # Install backend dependencies
          pm2 restart all || pm2 start server.js --name sabus_cubs
