name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    # Install and build frontend
    - name: Install frontend dependencies
      run: npm install

    - name: Build frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_CLOUD_NAME: ${{ secrets.VITE_CLOUD_NAME }}
        VITE_UPLOAD_PRESET: ${{ secrets.VITE_UPLOAD_PRESET }}
        VITE_PUBLISHABLE_KEY: ${{ secrets.VITE_PUBLISHABLE_KEY }}
        VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
        VITE_SENTRY_CLIENT_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_CLIENT_AUTH_TOKEN }}
        VITE_SENTRY_SERVER_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_SERVER_AUTH_TOKEN }}

    # Install backend dependencies and build backend
    - name: Install backend dependencies
      run: npm install --prefix server

    - name: Build backend
      run: npm run build --prefix server

    # Copy necessary non-code files into the api directory
    - name: Prepare backend for deployment
      run: |
        cp server/package.json api/package.json
        cp -R server/public api/public
        
    # Deploy frontend to Digital Ocean
    - name: Deploy frontend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./client/*"
        target: "/var/www/html/sabus_cubs/"

    # Deploy backend to Digital Ocean
    - name: Deploy backend to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./api/*"
        target: "/var/www/html/sabus_cubs/"

    # Restart backend with PM2
    - name: Restart backend with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/sabus_cubs/api
          npm install # Install backend dependencies
          pm2 restart all || pm2 start server.js --name sabus_cubs
